homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # base_url: 10.0.0.62:8123
  # Location required to calculate the time the sun rises and sets
  latitude: !secret HomeLatitude
  longitude: !secret HomeLongitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 23
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Time for some friendly names
  customize:
    media_player.hal:
      friendly_name: HAL
    device_tracker.amazingwifesphone:
      friendly_name: Aim
    device_tracker.briansmacbookpro:
      icon: mdi:laptop-mac


# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# to discover your IP: https://www.meethue.com/api/nupnp
# color lights: use the profile.csv to control the colors
# White Ambiance: use color_temp and brightness attributes not profile.csv
light:
  platform: hue
  host: 10.0.0.188

# media players
media_player Yamaha:
  - platform: yamaha
    host: !secret YamahaRecieverIP
    source_ignore:
      - "AUX"
      - "HDMI5"
      - "AV1"
      - "AV2"
      - "AV3"
      - "AV4"
      - "AV5"
      - "AV6"
      - "AUDIO1"
      - "AUDIO2"
      - "AirPlay"
      - "NET RADIO"
      - "Pandora"
      - "Rhapsody"
      - "SERVER"
      - "SiriusXM"
      - "TUNER"
      - "USB"
      - "V-AUX"
      - "iPod (USB)"
    source_names:
      HDMI1: "X-Box"
      HDMI2: "ChromeCast"
      HDMI3: "Cable"
      HDMI4: "RaspberryPi"

media_player hal:
  - platform: cast
    host: !secret ChromecastHalIP

media_player skynet:
  - platform: cast
    host: !secret ChromecastSkynetIP

media_player wopr:
  - platform: cast
    host: !secret ChromecastWoprIP

media_player GooglePlay:
  - platform: gpmdp
    host: 10.0.0.168

media_player mopidy:
  - platform: mpd
    host: 127.0.0.1

# Weather Prediction
sensor:
  - platform: darksky
    api_key: !secret DarkSkyAPI
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - nearest_storm_bearing
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_max
      - temperature_min
      - apparent_temperature_max
      - apparent_temperature_min
      - precip_intensity_max

camera:
  name: Orathai
  platform: generic
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.amazingwifesphone.attributes.latitude }},{{ states.device_tracker.amazingwifesphone.attributes.longitude }}&zoom=16&size=500x500&maptype=hybrid&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.amazingwifesphone.attributes.latitude }},{{ states.device_tracker.amazingwifesphone.attributes.longitude }}
  limit_refetch_to_url_change: true


# Text to speech
tts:
  platform: google

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: pi
  password: raspberry

#this section controls the location settings

device_tracker:
  - platform: icloud
    username: !secret iCloudAccount
    password: !secret iCloudPassword

zone:
  name: Home
  latitude: !secret HomeLatitude
  longitude: !secret HomeLongitude
  radius: 100
  icon: mdi:account-multiple

zone 1:
  name: Work
  latitude: !secret WorkLatitude
  longitude: !secret WorkLongitude
  radius: 100
  icon: mdi:domain

zone 2:
  name: Panyatiam Manor
  latitude: !secret PanyatiamLatitude
  longitude: !secret PanyatiamLongitude
  radius: 100
  icon: mdi:account-multiple


panel_iframe:
  music:
    title: 'Music'
    icon: 'mdi:music-box-outline'
    url: 'http://10.0.0.62:6680/mobile/index.html#/playback'

# UI Groupings
group:
  default_view:
    view: yes
    entities:
      - group.outside
      - media_player.yamaha_receiver
      - media_player.skynet
      - media_player.wopr
      - scene.movies
      - scene.Aim
      - group.people
      - group.lr_lights
      - group.dr_lights
      - group.br_lights
      - automation.leavehome
      - automation.arrivehome
      # - camera.orathai
  Media:
    name: Media
    view: yes
    entities:
      - group.MediaController
      - group.ChromeCast
      - media_player.mpd
  UpStairs:
    name: Up Stairs
    view: yes
    entities:
      - media_player.kitchen
      - media_player.living_room
  #Sub Groupings
  people:
    name: People
    entities:
      - device_tracker.strongbadia
      - device_tracker.amazingwifesphone
      - device_tracker.briansmacbookpro
  outside:
    name: Outside
    entities:
     - sensor.dark_sky_summary
     - sun.sun
     - sensor.dark_sky_temperature
     - sensor.dark_sky_wind_speed
  MediaController:
    name: Media
    entities:
      - media_player.yamaha_receiver
  ChromeCast:
    name: ChromeCast
    entities:
      - media_player.skynet
      - media_player.wopr
      - media_player.hal
  lr_lights:
    name: Living Room Lights
    entities:
      - light.living_center_rear
      - light.living_right_rear
      - light.living_left_rear
  dr_lights:
    name: Dining Room Lights
    entities:
      - light.dining_front
  kt_lights:
    name: Kitchen Lights
  br_lights:
    name: Bedroom Lights
    entities:
      - light.bedroom_brian

scene:
  - name: Movies
    entities:
      light.living_center_rear:
        state: on
        rgb_color: [29,4,0]
        color_temp: 153
        brightness: 1
      light.living_right_rear:
        state: on
        rgb_color: [29,4,0]
        color_temp: 153
        brightness: 1
      light.living_left_rear:
        state: on
        rgb_color: [29,4,0]
        color_temp: 153
        brightness: 1
      media_player.yamaha_receiver:
        - source: ChromeCast
        - is_volume_muted: false

  - name: Aim
    entities:
      light.living_center_rear:
        state: on
        rgb_color: [253,254,255]
        color_temp: 154
        brightness: 254
      light.living_right_rear:
        state: on
        rgb_color: [253,254,255]
        color_temp: 154
        brightness: 254
      light.living_left_rear:
        state: on
        rgb_color: [253,254,255]
        color_temp: 154
        brightness: 254
      media_player.yamaha_receiver:
        is_volume_muted: true

automation LeaveHome:
  alias: LeaveHome
  initial_state: true
  trigger:
    platform: zone
    entity_id: device_tracker.strongbadia
    zone: zone.home
    event: leave
  action:
    service: light.turn_off
    entity_id:
      - group.lr_lights
      - group.dr_lights
      - group.br_lights

automation ArriveHome:
  alias: ArriveHome
  initial_state: true
  trigger:
    platform: zone
    entity_id: device_tracker.strongbadia
    zone: zone.home
    event: enter
  action:
    service: light.turn_on
    entity_id:
      - group.lr_lights
      - group.dr_lights
      - group.br_lights
